language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3
# blocklist branches
branches:
  except:
  - requires-io-master
install:
- pip install -r requirements-test.txt
- pip install -e .[tests] coveralls wheel
script:
- py.test -v --cov src/pytest_redis tests/
- pylama
- pyroma .
after_success:
- coveralls
jobs:
  include:
    - stage: xdist
      python: 3.6
      script: py.test -n 1 --cov src/pytest_redis tests
    - stage: deploy
      python: 3.6
      if: tag IS present
      script: skip
      deploy:
        provider: pypi
        user: thearoom
        password:
          secure: TI7WRNYiYo9j5QP2LfRDQfV5h60918qNNqHr7nivjn0NehvGB2/tvUwhhBqQBpQY0dRz+0mR4EG0wSucqBkKPUV+bWBz0RajaV/NanKCn8Ug+xAQdSALjHCdl3K9ukQhoqLV8Z8ueSQzIbYt0B3Wblv6jVjncIyquR3O7WLhjMoC0a6DBO9b2tLTv5weIJ/JIDz3AWcJSB65nXLLjP2/9EYR1XhFHYHqh2EKqL/UBZx4GJb/5mPGy96mZTtZMVs7y9MfB5wP39/5tpVIt4rUOJMwO+8xPZAseCKb3VZHJzV/fGuMZpGDZ2Kt3lQqdrSLCErLGVT5K84zvBEZuYU3ZFK9QtNNvj+EOy+uu4gl7dz/BHjDdyqxg/KJkPFZE4YlIrxCncTt2PIrOKCJt5eeMVc99eK9gICK1mmIxP4U9i0ZwaTU1JxWuwdxLpkIBFkGnCfrluH3fxF/EOMHoiFcLLc52CyRTb9DiOL6lRytol+HlOcKx0WDQ55pY1vbmFUhnNH10glDLd3OAr8A0vfaJxA3CNTrkYUP2c9gtyawXw7rn7YkIs14YL+vsfP17J1uHlDaiAhuSaHTGd4qfooKoWbAYrf97+IBEqaQI2cy8FE1ROOXHRbdjtovdUVo6XicxBswtc0nGi1IVr5bsLoYhzq5igunDtX5MMhIHxAUIyI=
        on:
          tags: true
          all_branches: true
          repo: ClearcodeHQ/pytest-redis
        distributions: bdist_wheel
